api_key:
  code: "176f5d1935a3527be17dad602b384ccca2be5675" 
  icinga: "usminfo"
  camera: "primo:primo@"
twitter:
  consumer_key: "v5eAd32JJQMCwGBFMboLA"
  consumer_secret: "VZBpAvFjZkLIeDztFI3rPDSzV1f9UKmRTo0SDnfgQ"
  oauth_token: "38722219-CciRDgH2QdK55Nd0IPyyMu7jhdBlNP4g2EIllM9aC"
  oauth_token_secret: "Mvu4hke15YSKojTYLCiHT62Ldb1o6daQnpJZeBF3c"